sudo: required
services:
  - docker

before_install:
  - docker build -t gagana/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gagana/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-west-2-362628047255"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"